// create an array of 9 objects called artwork that can be exported that has a property called src that is a string to a image on the asset folder on the public folder
export const artworks = [
  {
    src: "/artwork/artwork-1.png",
    category: "Abstract",
    title: "Abstract 1",
    description: "Abstract 1",
    price: 33,
    id: 0,
    active: true,
    variations: [1, 2, 3, 4],
    prompt: "prompt 0",
  },
  {
    src: "/artwork/artwork-2.png",
    category: "Abstract",
    title: "Abstract 1",
    description: "Abstract 1",
    price: 33,
    id: 1,
    active: true,
    variations: [1, 2, 3, 4],
    prompt: "prompt 1",

  },
  {
    src: "/artwork/artwork-3.png",
    category: "Abstract",
    title: "Abstract 1",
    description: "Abstract 1",
    price: 33,
    id: 2,
    active: true,
    variations: [0, 1],
  },
  {
    src: "/artwork/artwork-4.png",
    category: "Abstract",
    title: "Abstract 1",
    description: "Abstract 1",
    price: 33,
    id: 3,
    active: true,
    variations: [0, 1],
  },
  {
    src: "/artwork/artwork-5.png",
    category: "Abstract",
    title: "Abstract 1",
    description: "Abstract 1",
    price: 33,
    id: 4,
    active: true,
    variations: [0, 1],
  },
  // {
  //   src: "/artwork/artwork-4.png",
  //   category: "Abstract",
  //   title: "Abstract 1",
  //   description: "Abstract 1",
  //   price: 33,
  //   id: "4",
  //   active: true,
  // },
  // {
  //   src: "/artwork/artwork-5.png",
  //   category: "Realistic",
  //   title: "Abstract 1",
  //   description: "Abstract 1",
  //   price: 33,
  //   id: "5",
  //   active: true,
  // },
  // {
  //   src: "/artwork/artwork-6.png",
  //   category: "2D",
  //   title: "Abstract 1",
  //   description: "Abstract 1",
  //   price: 33,
  //   id: "6",
  //   active: true,
  // },
  // {
  //   src: "/artwork/artwork-7.png",
  //   category: "2D",
  //   title: "Abstract 1",
  //   description: "Abstract 1",
  //   price: 33,
  //   id: "7",
  //   active: true,
  // },
  // {
  //   src: "/artwork/artwork-8.png",
  //   category: "2D",
  //   title: "Abstract 1",
  //   description: "Abstract 1",
  //   price: 33,
  //   id: "8",
  //   active: true,
  // },
  // {
  //   src: "/artwork/artwork-9.png",
  //   category: "2D",
  //   title: "Abstract 1",
  //   description: "Abstract 1",
  //   price: 33,
  //   id: "9",
  //   active: true,
  // },
  // {
  //   src: "/artwork/artwork-10.png",
  //   category: "2D",
  //   title: "Abstract 1",
  //   description: "Abstract 1",
  //   price: 33,
  //   id: "10",
  //   active: true,
  // },
  // {
  //   src: "/artwork/artwork-11.png",
  //   category: "2D",
  //   title: "Abstract 1",
  //   description: "Abstract 1",
  //   price: 33,
  //   id: "11",
  //   active: true,
  // },
  // {
  //   src: "/artwork/artwork-12.png",
  //   category: "2D",
  //   title: "Abstract 1",
  //   description: "Abstract 1",
  //   price: 33,
  //   id: "12",
  //   active: true,
  // },
];
